# Copyright 2023 Geoffrey R. Scheller
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Module grscheller.datastructure.fclarray - constant length array.

Module implementing an mutable fixed length data structure with O(1) data
access. All mutating methods are guaranteed not to change the length of the
data structure.

None values are not allowed in this data structures. An immutable default value
is set upon instantiating. If no default value is given, the empty tuple () is
used in lieu of None, but is not set as the default value. Method which return
new FCLArray values can set a different default value for the new instance.
"""

from __future__ import annotations

__all__ = ['FCLArray']
__author__ = "Geoffrey R. Scheller"
__copyright__ = "Copyright (c) 2023 Geoffrey R. Scheller"
__license__ = "Appache License 2.0"

from typing import Any, Callable, Iterator, Iterable
from itertools import chain, cycle
from .core.iterlib import merge, exhaust
from .core.clarray_base import CLArrayBase
from .core.fp import FP

class FCLArray(CLArrayBase, FP):
    """Functional Constant Length Array

    Class implementing a mutable fixed length array data structure whose
    mutaing methods are guaranteed not to change the length of the data
    structure.

    If size set to None, size to data provided.
    If size > 0, pad data on right with default value or slice off trailing data.
    If size < 0, pad data on left with default value or slice off initial data.

    Does not permits storing None as a value. If a default value is not set, the
    empty tuple () is used in lieu of None, but () is not set as the default
    value.
    """
    def __str__(self):
        return '[|' + ', '.join(map(repr, self)) + '|]'

    def map(self, f: Callable[[Any], Any], size: int|None=None,
            noneIter: Iterator|None=None, default: Any|None=None) -> Type[CLArrayBase]:
        """Apply function f over the FCLArray contents. Return a new FCLArray
        with the mapped contents. Size to the data unless size is given. If
        noneIter is not given, use default to create the none iterator. If
        default is not given, use the value from the FCLArray being mapped.
        """
        match (noneIter, default):
            case (None, None):
                default = self._default
                noneIter = cycle((default,))
            case (None, default):
                noneIter = cycle((default,))
            case (noneIter, None):
                # Careful: noneIter might be infinite!
                default = self._default

        if size is None:
            return FCLArray(*map(f, self), noneIter=noneIter, default=default)
        else:
            return FCLArray(*map(f, self), size=size, noneIter=noneIter, default=default)

    def flatMap(self, f: Callable[[Any], FCLArray],
                size: int|None=None,
                noneIter: Iterator|None=None,
                default: Any|None=None) -> FCLArray:
        """Map f across self and flatten result by concatenating the FCLArray
        elements generated by f. If a default value is not given, use the
        default value of the FLArray being flatMapped if it has been set,
        otherwise leave it unset.

        Note: Any default values of the FLArrays created by f need not have
        anything to do with the default value of the FPArray being flat mapped
        over.
        """
        if (noneIter, default) == (None, None):
            default = self._default

        return FCLArray(
            *chain(*self.map(f)), size=size, noneIter=noneIter, default=default
        )

    def mergeMap(self, f: Callable[[Any], FCLArray],
                 size: int|None=None,
                 noneIter: Iterator|None=None,
                 default: Any|None=None) -> FCLArray:
        """Map f across self and flatten result by merging the FCLArray elements
        generated by f until the first is exhausted. If a default value is not
        given, use the default value of the FLArray being flatMapped if it has
        been set, otherwise leave it unset.
        """
        if (noneIter, default) == (None, None):
            noneIter = self._none

        return FCLArray(
            *merge(*self.map(f)), size=size, noneIter=noneIter, default=default
        )

    def exhastMap(self, f: Callable[[Any], FCLArray|Iterable],
                  size: int|None=None,
                  noneIter: Iterator|None=None,
                  default: Any|None=None) -> FCLArray:
        """Map f across self and flatten result by merging the FCLArray elements
        generated by f until all are exhausted. If a default value is not given,
        use the default value of the FLArray being flatMapped if it has been
        set, otherwise leave it unset.
        """
        if (noneIter, default) == (None, None):
            noneIter = self._none

        return FCLArray(
            *exhaust(*self.map(f)), size=size, noneIter=noneIter, default=default
        )

if __name__ == "__main__":
    pass
